[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  publish = ".next"
  environment = { NEXT_PUBLIC_DATABASE_URL = "postgresql://postgres:Axe123@nline@db.ucqqmycyxgjpezknhzuy.supabase.co:5432/postgres" }

[[plugins]]
  package = "@netlify/next"

[dev]
  command = "npm run dev"
  port = 3000
