[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  base    = "app"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://postgres:Axe123@nline@db.ucqqmycyxgjpezknhzuy.supabase.co:5432/postgres"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
