[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  base    = "app"
  publish = ".next"


[build.environment]
  PRISMA_GENERATE_SKIP_VALIDATE = "true"
  

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
